sten.wad
maps/de_fastline2.bsp
maps/de_fastline2.res
gfx/env/morningdewbk.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewft.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewup.tga
sound/sten/soul_search.wav
sound/sten/fusion_feelings.wav
sound/ambience/fastline/fastline_station2.wav
sound/ambience/fastline/fastline_station3.wav
sound/ambience/fastline/fastline_station4.wav
sound/ambience/fastline/fastline_turnreject.wav
sound/ambience/fastline/misc_vendmachine_loop.wav
models/props/lamp_portable_standup.mdl
models/props/scaffold.mdl
models/props/wires_still.mdl
models/props/plant_potted.mdl
models/props/tree_japan_maple_orange.mdl
models/props/rails_subway.mdl
overviews/de_fastline2.txt
overviews/de_fastline2.bmp