sten.wad
maps/de_fastline2.bsp
maps/de_fastline2.res
gfx/env/c2nitebk.tga
gfx/env/c2nitedn.tga
gfx/env/c2niteft.tga
gfx/env/c2nitelf.tga
gfx/env/c2nitert.tga
gfx/env/c2niteup.tga
sound/sten/soul_search.wav
sound/sten/fusion_feelings.wav
sound/sten/trace_mileshigh.wav
sound/sten/reignofthetec2k.wav
sound/sten/justice_soothemysoul.wav
sound/ambience/fastline/fastline_station2.wav
sound/ambience/fastline/fastline_station3.wav
sound/ambience/fastline/fastline_station4.wav
sound/ambience/fastline/fastline_turnreject.wav
sound/ambience/fastline/misc_vendmachine_loop.wav
models/props/lamp_portable_standup_02.mdl
models/props/scaffold.mdl
models/props/scaffold_short.mdl
models/props/wires_still.mdl
models/props/plant_potted.mdl
models/props/tree_japan_maple_orange.mdl
models/props/rails_subway.mdl
models/props/trash.mdl
models/sten/boombox.mdl
models/props/rails_subway.mdl
models/props/table_folding.mdl
models/props/box_group_big2.mdl
models/props/chair_folding.mdl
models/props/dolly.mdl
overviews/de_fastline2.txt
overviews/de_fastline2.bmp